FROM python:3.9-slim
WORKDIR /app
COPY . .
#RUN python3 -m venv venv\
#    . venv/bin/activate 
# Монтирование кеша pip с docker host
RUN pip install -r requirements.txt
#EXPOSE 5000
CMD ["python", "main.py"]