version: '3.8'
services:

  reverse-proxy:
    image: haproxy:2.4
    restart: always
    networks:
      #backend: {}
      - backend
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./haproxy/reverse/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:rw 
    depends_on: 
      - web

  ingress-proxy:
    image: nginx:1.21.1
    restart: always
    #network_mode: host
    networks:
      - backend
    volumes:
      - ./nginx/ingress/default.conf:/etc/nginx/conf.d/default.conf:rw
      - ./nginx/ingress/nginx.conf:/etc/nginx/nginx.conf:rw
    ports:
     - "0.0.0.0:8090:8090"
    depends_on:
      - reverse-proxy

networks:
  backend:
    driver: bridge
    ipam:
     config:
       - subnet: 172.20.0.0/24
